2015-11-05 17:44:21,756 - streamparse.storm.component - ERROR - Exception in ParseMessage.run()
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/streamparse/storm/component.py", line 489, in run
    self._run()
  File "/usr/lib/python2.7/site-packages/streamparse/storm/bolt.py", line 219, in _run
    self.process(tup)
  File "bolts/parsemessage.py", line 10, in process
    fields = measure.value.split(',')
AttributeError: 'dict' object has no attribute 'value'
